apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: newtransaction
  namespace: dapr-frauddetaction
spec:
  type: bindings.mqtt
  version: v1
  metadata:
  - name: url
    value: mqtt://localhost:1883
  - name: topic
    value: transaction/new
  - name: consumerID
    value: "{uuid}"
scopes:
  - transactionservice